[versions]
kotlin = "2.2.20"
coroutines = "1.10.2"
detekt = "1.23.8"
quick = "0.1"

fml = "1.4.5"
kotlin_language = "1.0.1"
kawakaze = "1.1.1"


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

quick = { id = "io.github.yukiminju.plugin.quick", version.ref = "quick" }
fml = { id = "fml-loom", version.ref = "fml" }

[libraries]
# kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
# mods
kotlinLanguage = { group = "cute.neko.mite", name = "kotlin-language", version.ref = "kotlin_language" }
kawakazeLib = { group = "cute.neko.mite", name ="kawakaze-lib", version.ref = "kawakaze" }

[bundles]
kotlins = ["kotlin-stdlib", "kotlin-reflect", "kotlinx-coroutines"]